-- Genera destinos para TODOS los países del catálogo (148 single-country).
-- Nombres ES via Intl.DisplayNames, banderas del ISO, región mapeada. Idempotente:
-- solo inserta si el iso_match no existe ya como destino. (i18n ES/EN/PT en translations.ts)
insert into destination (slug, name, code, region, flag, iso_match, sort_order)
select v.slug, v.name, v.code, v.region, v.flag, v.iso_match, v.sort_order
from (values
  ('andorra','Andorra','AD','Europe','🇦🇩','AD',200),
  ('emiratos-arabes-unidos','Emiratos Árabes Unidos','AE','Asia','🇦🇪','AE',201),
  ('afganistan','Afganistán','AF','Asia','🇦🇫','AF',202),
  ('antigua-y-barbuda','Antigua y Barbuda','AG','Americas','🇦🇬','AG',203),
  ('anguila','Anguila','AI','Americas','🇦🇮','AI',204),
  ('albania','Albania','AL','Europe','🇦🇱','AL',205),
  ('armenia','Armenia','AM','Asia','🇦🇲','AM',206),
  ('curazao','Curazao','AN','Americas','🇦🇳','AN',207),
  ('argentina','Argentina','AR','Americas','🇦🇷','AR',208),
  ('austria','Austria','AT','Europe','🇦🇹','AT',209),
  ('australia','Australia','AU','Asia','🇦🇺','AU',210),
  ('azerbaiyan','Azerbaiyán','AZ','Asia','🇦🇿','AZ',211),
  ('bosnia-y-herzegovina','Bosnia y Herzegovina','BA','Europe','🇧🇦','BA',212),
  ('barbados','Barbados','BB','Americas','🇧🇧','BB',213),
  ('banglades','Bangladés','BD','Asia','🇧🇩','BD',214),
  ('belgica','Bélgica','BE','Europe','🇧🇪','BE',215),
  ('bulgaria','Bulgaria','BG','Europe','🇧🇬','BG',216),
  ('barein','Baréin','BH','Asia','🇧🇭','BH',217),
  ('bolivia','Bolivia','BO','Americas','🇧🇴','BO',218),
  ('brasil','Brasil','BR','Americas','🇧🇷','BR',219),
  ('bahamas','Bahamas','BS','Americas','🇧🇸','BS',220),
  ('bielorrusia','Bielorrusia','BY','Europe','🇧🇾','BY',221),
  ('belice','Belice','BZ','Americas','🇧🇿','BZ',222),
  ('canada','Canadá','CA','Americas','🇨🇦','CA',223),
  ('republica-democratica-del-congo','República Democrática del Congo','CD','Africa','🇨🇩','CD',224),
  ('congo','Congo','CG','Africa','🇨🇬','CG',225),
  ('suiza','Suiza','CH','Europe','🇨🇭','CH',226),
  ('chile','Chile','CL','Americas','🇨🇱','CL',227),
  ('china','China','CN','Asia','🇨🇳','CN',228),
  ('colombia','Colombia','CO','Americas','🇨🇴','CO',229),
  ('costa-rica','Costa Rica','CR','Americas','🇨🇷','CR',230),
  ('cabo-verde','Cabo Verde','CV','Africa','🇨🇻','CV',231),
  ('chipre','Chipre','CY','Europe','🇨🇾','CY',232),
  ('chequia','Chequia','CZ','Europe','🇨🇿','CZ',233),
  ('alemania','Alemania','DE','Europe','🇩🇪','DE',234),
  ('dinamarca','Dinamarca','DK','Europe','🇩🇰','DK',235),
  ('dominica','Dominica','DM','Americas','🇩🇲','DM',236),
  ('republica-dominicana','República Dominicana','DO','Americas','🇩🇴','DO',237),
  ('argelia','Argelia','DZ','Africa','🇩🇿','DZ',238),
  ('ecuador','Ecuador','EC','Americas','🇪🇨','EC',239),
  ('estonia','Estonia','EE','Europe','🇪🇪','EE',240),
  ('egipto','Egipto','EG','Africa','🇪🇬','EG',241),
  ('espana','España','ES','Europe','🇪🇸','ES',242),
  ('finlandia','Finlandia','FI','Europe','🇫🇮','FI',243),
  ('fiyi','Fiyi','FJ','Asia','🇫🇯','FJ',244),
  ('islas-feroe','Islas Feroe','FO','Europe','🇫🇴','FO',245),
  ('francia','Francia','FR','Europe','🇫🇷','FR',246),
  ('gabon','Gabón','GA','Africa','🇬🇦','GA',247),
  ('reino-unido','Reino Unido','GB','Europe','🇬🇧','GB',248),
  ('granada','Granada','GD','Americas','🇬🇩','GD',249),
  ('georgia','Georgia','GE','Asia','🇬🇪','GE',250),
  ('guayana-francesa','Guayana Francesa','GF','Americas','🇬🇫','GF',251),
  ('ghana','Ghana','GH','Africa','🇬🇭','GH',252),
  ('gibraltar','Gibraltar','GI','Europe','🇬🇮','GI',253),
  ('guadalupe','Guadalupe','GP','Americas','🇬🇵','GP',254),
  ('grecia','Grecia','GR','Europe','🇬🇷','GR',255),
  ('guatemala','Guatemala','GT','Americas','🇬🇹','GT',256),
  ('guam','Guam','GU','Asia','🇬🇺','GU',257),
  ('rae-de-hong-kong-china','RAE de Hong Kong (China)','HK','Asia','🇭🇰','HK',258),
  ('honduras','Honduras','HN','Americas','🇭🇳','HN',259),
  ('croacia','Croacia','HR','Europe','🇭🇷','HR',260),
  ('hungria','Hungría','HU','Europe','🇭🇺','HU',261),
  ('indonesia','Indonesia','ID','Asia','🇮🇩','ID',262),
  ('irlanda','Irlanda','IE','Europe','🇮🇪','IE',263),
  ('israel','Israel','IL','Asia','🇮🇱','IL',264),
  ('india','India','IN','Asia','🇮🇳','IN',265),
  ('irak','Irak','IQ','Asia','🇮🇶','IQ',266),
  ('islandia','Islandia','IS','Europe','🇮🇸','IS',267),
  ('italia','Italia','IT','Europe','🇮🇹','IT',268),
  ('jamaica','Jamaica','JM','Americas','🇯🇲','JM',269),
  ('jordania','Jordania','JO','Asia','🇯🇴','JO',270),
  ('japon','Japón','JP','Asia','🇯🇵','JP',271),
  ('kenia','Kenia','KE','Africa','🇰🇪','KE',272),
  ('kirguistan','Kirguistán','KG','Asia','🇰🇬','KG',273),
  ('camboya','Camboya','KH','Asia','🇰🇭','KH',274),
  ('san-cristobal-y-nieves','San Cristóbal y Nieves','KN','Americas','🇰🇳','KN',275),
  ('corea-del-sur','Corea del Sur','KR','Asia','🇰🇷','KR',276),
  ('kuwait','Kuwait','KW','Asia','🇰🇼','KW',277),
  ('islas-caiman','Islas Caimán','KY','Americas','🇰🇾','KY',278),
  ('kazajistan','Kazajistán','KZ','Asia','🇰🇿','KZ',279),
  ('laos','Laos','LA','Asia','🇱🇦','LA',280),
  ('santa-lucia','Santa Lucía','LC','Americas','🇱🇨','LC',281),
  ('liechtenstein','Liechtenstein','LI','Europe','🇱🇮','LI',282),
  ('sri-lanka','Sri Lanka','LK','Asia','🇱🇰','LK',283),
  ('lituania','Lituania','LT','Europe','🇱🇹','LT',284),
  ('luxemburgo','Luxemburgo','LU','Europe','🇱🇺','LU',285),
  ('letonia','Letonia','LV','Europe','🇱🇻','LV',286),
  ('marruecos','Marruecos','MA','Africa','🇲🇦','MA',287),
  ('moldavia','Moldavia','MD','Europe','🇲🇩','MD',288),
  ('montenegro','Montenegro','ME','Europe','🇲🇪','ME',289),
  ('madagascar','Madagascar','MG','Africa','🇲🇬','MG',290),
  ('macedonia-del-norte','Macedonia del Norte','MK','Europe','🇲🇰','MK',291),
  ('mongolia','Mongolia','MN','Asia','🇲🇳','MN',292),
  ('rae-de-macao-china','RAE de Macao (China)','MO','Asia','🇲🇴','MO',293),
  ('montserrat','Montserrat','MS','Americas','🇲🇸','MS',294),
  ('malta','Malta','MT','Europe','🇲🇹','MT',295),
  ('mauricio','Mauricio','MU','Africa','🇲🇺','MU',296),
  ('maldivas','Maldivas','MV','Asia','🇲🇻','MV',297),
  ('malaui','Malaui','MW','Africa','🇲🇼','MW',298),
  ('mexico','México','MX','Americas','🇲🇽','MX',299),
  ('malasia','Malasia','MY','Asia','🇲🇾','MY',300),
  ('niger','Níger','NE','Africa','🇳🇪','NE',301),
  ('nigeria','Nigeria','NG','Africa','🇳🇬','NG',302),
  ('nicaragua','Nicaragua','NI','Americas','🇳🇮','NI',303),
  ('paises-bajos','Países Bajos','NL','Europe','🇳🇱','NL',304),
  ('noruega','Noruega','NO','Europe','🇳🇴','NO',305),
  ('nepal','Nepal','NP','Asia','🇳🇵','NP',306),
  ('nueva-zelanda','Nueva Zelanda','NZ','Asia','🇳🇿','NZ',307),
  ('oman','Omán','OM','Asia','🇴🇲','OM',308),
  ('panama','Panamá','PA','Americas','🇵🇦','PA',309),
  ('peru','Perú','PE','Americas','🇵🇪','PE',310),
  ('filipinas','Filipinas','PH','Asia','🇵🇭','PH',311),
  ('pakistan','Pakistán','PK','Asia','🇵🇰','PK',312),
  ('polonia','Polonia','PL','Europe','🇵🇱','PL',313),
  ('puerto-rico','Puerto Rico','PR','Americas','🇵🇷','PR',314),
  ('territorios-palestinos','Territorios Palestinos','PS','Asia','🇵🇸','PS',315),
  ('portugal','Portugal','PT','Europe','🇵🇹','PT',316),
  ('paraguay','Paraguay','PY','Americas','🇵🇾','PY',317),
  ('catar','Catar','QA','Asia','🇶🇦','QA',318),
  ('reunion','Reunión','RE','Africa','🇷🇪','RE',319),
  ('rumania','Rumanía','RO','Europe','🇷🇴','RO',320),
  ('serbia','Serbia','RS','Europe','🇷🇸','RS',321),
  ('rusia','Rusia','RU','Europe','🇷🇺','RU',322),
  ('ruanda','Ruanda','RW','Africa','🇷🇼','RW',323),
  ('arabia-saudi','Arabia Saudí','SA','Asia','🇸🇦','SA',324),
  ('suecia','Suecia','SE','Europe','🇸🇪','SE',325),
  ('singapur','Singapur','SG','Asia','🇸🇬','SG',326),
  ('eslovenia','Eslovenia','SI','Europe','🇸🇮','SI',327),
  ('eslovaquia','Eslovaquia','SK','Europe','🇸🇰','SK',328),
  ('senegal','Senegal','SN','Africa','🇸🇳','SN',329),
  ('el-salvador','El Salvador','SV','Americas','🇸🇻','SV',330),
  ('islas-turcas-y-caicos','Islas Turcas y Caicos','TC','Americas','🇹🇨','TC',331),
  ('chad','Chad','TD','Africa','🇹🇩','TD',332),
  ('tailandia','Tailandia','TH','Asia','🇹🇭','TH',333),
  ('tunez','Túnez','TN','Africa','🇹🇳','TN',334),
  ('turquia','Turquía','TR','Asia','🇹🇷','TR',335),
  ('taiwan','Taiwán','TW','Asia','🇹🇼','TW',336),
  ('tanzania','Tanzania','TZ','Africa','🇹🇿','TZ',337),
  ('ucrania','Ucrania','UA','Europe','🇺🇦','UA',338),
  ('uganda','Uganda','UG','Africa','🇺🇬','UG',339),
  ('estados-unidos','Estados Unidos','US','Americas','🇺🇸','US',340),
  ('uruguay','Uruguay','UY','Americas','🇺🇾','UY',341),
  ('uzbekistan','Uzbekistán','UZ','Asia','🇺🇿','UZ',342),
  ('san-vicente-y-las-granadinas','San Vicente y las Granadinas','VC','Americas','🇻🇨','VC',343),
  ('venezuela','Venezuela','VE','Americas','🇻🇪','VE',344),
  ('islas-virgenes-britanicas','Islas Vírgenes Británicas','VG','Americas','🇻🇬','VG',345),
  ('vietnam','Vietnam','VN','Asia','🇻🇳','VN',346),
  ('sudafrica','Sudáfrica','ZA','Africa','🇿🇦','ZA',347)
) as v(slug, name, code, region, flag, iso_match, sort_order)
where not exists (select 1 from destination d where d.iso_match = v.iso_match)
on conflict (slug) do nothing;
